# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'Journey' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Journey
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Nuke', '~> 6.0'

end
